# This is a basic workflow to help you get started with Actions

# This is the workflow name, which will be show up in Actions Tab's Left-panel
name: CI   

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # All
  schedule:
    - cron: 0 12 * * 1
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # The name of a job is ramdom, you could name it anything you want
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # The steps are running in sequencial-order
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Basically, it a module of code, or a 3rd-function that you could use in your job
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        shell: bash

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
